/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //docs: [{type: 'autogenerated', dirName: '.'}],

  docs: [
    'intro',
    {
      type: 'category',
      label: 'Getting Started',
      link: {
        type: 'doc',
        id: 'getting-started/overview',
      },
      collapsed: false,
      items: [
        "getting-started/quickstart",
        {
          type: 'category',
          label: 'DataSQRL Training',
          link: {
            type: 'doc',
            id: 'getting-started/intro/overview',
          },
          items: [
            'getting-started/intro/data-sources',
            'getting-started/intro/sqrl',
            'getting-started/intro/api',
            'getting-started/intro/server',
            'getting-started/intro/advanced',
          ],
        },
        'getting-started/concepts/datasqrl',
        'getting-started/concepts/sqrl',
        "getting-started/concepts/why-datasqrl",
        'getting-started/comparison/overview',


/*        {
          type: 'category',
          label: 'Tutorials',
          link: {
            type: 'generated-index',
            title: 'DataSQRL Tutorials',
            description: "These tutorials apply DataSQRL to various use cases and industries."
          },
          items: [
            'getting-started/tutorials/telco',
          ],
        },
*/
      ],
    },
    {
      type: 'category',
      label: 'How-to Guides',
      link: {
        type: 'doc',
        id: 'guides/overview',
      },
      items: [
        {
          type: 'category',
          label: 'Sources & Sinks',
          link: {
            type: 'doc',
            id: 'guides/sources/overview',
          },
          items: [
            'guides/sources/files',
            'guides/sources/kafka',
          ],
        },
        {
          type: 'category',
          label: 'SQRL',
          link: {
            type: 'doc',
            id: 'guides/sqrl/overview',
          },
          items: [
            'guides/sqrl/deduplicate-stream',
          ],
        },
        {
          type: 'category',
          label: 'API',
          link: {
            type: 'doc',
            id: 'guides/api/overview',
          },
          items: [
            'guides/api/graphql-js',
          ],
        },
        {
          type: 'category',
          label: 'Operations',
          link: {
            type: 'generated-index',
            title: 'How to Operate and Maintain DataSQRL',
            description: "These guides help you run DataSQRL in development and production."
          },
          items: [
            'guides/operations/dev-mode',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Reference Documentation',
      link: {
        type: 'doc',
        id: 'reference/overview',
      },
      items: [
        {
          type: 'category',
          label: 'Sources & Sinks',
          link: {
            type: 'doc',
            id: 'reference/sources/overview',
          },
          items: [
            'reference/sources/api',
          ],
        },
        {
          type: 'category',
          label: 'SQRL',
          link: {
            type: 'doc',
            id: 'reference/sqrl/overview',
          },
          items: [
            'reference/sqrl/grammar',
            'reference/sqrl/table',
            'reference/sqrl/relationship',
            'reference/sqrl/time',
            {
              type: 'category',
              label: 'Functions',
              link: {
                type: 'generated-index',
                title: 'Functions in SQRL',
                description: "Functions make your life so much easier and your SQRL scripts so much shorter. If we could \
                only remember them when we need them. Luckily you have this reference list of functions to look them up:"
              },
              items: [
                'reference/sqrl/functions/string-fct',
                'reference/sqrl/functions/time-fct',
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'API',
          link: {
            type: 'doc',
            id: 'reference/api/overview',
          },
          items: [
            'reference/api/graphql-api',
            'reference/api/subscriptions',
            'reference/api/access-control',
            'reference/api/graphql-primer',
          ],
        },
        {
          type: 'category',
          label: 'Operations',
          link: {
            type: 'doc',
            id: 'reference/operations/overview',
          },
          items: [
            'reference/operations/cmd',
            'reference/operations/configuration',
            'reference/operations/monitoring',
            'reference/operations/optimizer',
          ],
        },
        {
          type: 'category',
          label: 'Key Concepts',
          link: {
            type: 'generated-index',
            title: 'Key Concepts in DataSQRL',
            description: "Knowing the key concepts in DataSQRL is useful for understanding how it works and how to use it. \
                Think Oxford dictionary for data nerds. Sounds fun? Read on! Doesn't? Then imagine Benedict Cumberbatch reading it to you with a British accent."
          },
          items: [
            'reference/concepts/data-service',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Developer Documentation',
      link: {
        type: 'doc',
        id: 'dev/overview',
      },
      items: [
        'dev/philosophy',
        {
          type: 'category',
          label: 'DataSQRL Architecture',
          link: {
            type: 'doc',
            id: 'dev/architecture/overview',
          },
          items: [
            'dev/architecture/data-source',
            'dev/architecture/ingest',
          ],
        },
        'dev/contribute'
      ],
    },
    {
      type: 'category',
      label: 'DataSQRL Process',
      link: {
        type: 'doc',
        id: 'process/intro',
      },
      items: [
        'process/customer-focused',
        'process/responsive',
        'process/integrated'
      ],
    },
  ],

};

module.exports = sidebars;
